<?php

namespace App\Http\Controllers\Central;

use App\Http\Controllers\Controller;
use App\Jobs\GenerateTenantDataExportJob;
use App\Models\Central\AuditLog;
use App\Models\Central\Tenant;
use App\Models\Central\TenantDataExportRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class TenantDataExportController extends Controller
{
    public function index(Request $request)
    {
        $query = TenantDataExportRequest::query()
            ->with('tenant:id,name,email,slug')
            ->orderByDesc('id');

        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        if ($request->filled('tenant_id')) {
            $query->where('tenant_id', (int) $request->tenant_id);
        }

        $exports = $query->paginate(20)->withQueryString();

        return view('central.pages.data-exports', compact('exports'));
    }

    public function approve(int $id)
    {
        $export = TenantDataExportRequest::query()->findOrFail($id);
        abort_unless($export->isPending(), 422, 'This request is not pending.');

        $this->queueApproved($export, 'Tenant request approved');

        return back()->with('success', 'Export approved. The package is being prepared.');
    }

    public function reject(Request $request, int $id)
    {
        $export = TenantDataExportRequest::query()->findOrFail($id);
        abort_unless($export->isPending(), 422, 'This request is not pending.');

        $validated = $request->validate([
            'rejection_note' => ['required', 'string', 'min:4', 'max:1000'],
        ]);

        $sa = Auth::guard('super_admin')->user();

        $export->forceFill([
            'status'         => 'rejected',
            'rejection_note' => $validated['rejection_note'],
            'reviewed_by'    => $sa?->id,
            'reviewed_at'    => now(),
        ])->save();

        AuditLog::record(
            'tenant.data_export_rejected',
            (int) $export->tenant_id,
            'super_admin',
            $sa?->id,
            $sa?->name,
            [
                'subject_type' => 'tenant_data_export_request',
                'subject_id'   => $export->id,
                'description'  => 'Workspace data export rejected',
                'after'        => ['note' => $validated['rejection_note']],
            ]
        );

        return back()->with('success', 'Request rejected.');
    }

    public function generateNow(int $tenantId)
    {
        $tenant = Tenant::query()->findOrFail($tenantId);
        $open = TenantDataExportRequest::inProgressForTenant((int) $tenant->id);

        if ($open && in_array($open->status, ['approved', 'processing'], true)) {
            return back()->with('error', 'An export is already being prepared for this tenant.');
        }

        $sa = Auth::guard('super_admin')->user();

        if ($open && $open->isPending()) {
            $this->queueApproved($open, 'Pending request approved via Generate now');

            return back()->with('success', 'Pending request approved. The package is being prepared.');
        }

        $export = TenantDataExportRequest::query()->create([
            'tenant_id'         => $tenant->id,
            'requested_by_name' => $sa?->name,
            'requested_by_type' => 'super_admin',
            'reason'            => 'Generated by Super Admin',
            'status'            => 'pending',
        ]);

        $this->queueApproved($export, 'Generated by Super Admin');

        return back()->with('success', 'Export queued. Download it here when ready.');
    }

    public function download(int $id): BinaryFileResponse
    {
        $export = TenantDataExportRequest::query()->findOrFail($id);
        abort_unless($export->isReady(), 404, 'Export file is not ready.');

        $path = $export->absolutePath();
        abort_unless($path && is_file($path), 404);

        $export->forceFill([
            'download_count'     => $export->download_count + 1,
            'last_downloaded_at' => now(),
        ])->save();

        return response()->download($path, basename($path), [
            'Content-Type' => 'application/zip',
        ]);
    }

    private function queueApproved(TenantDataExportRequest $export, string $description): void
    {
        $sa = Auth::guard('super_admin')->user();

        $export->forceFill([
            'status'      => 'approved',
            'reviewed_by' => $sa?->id,
            'reviewed_at' => now(),
        ])->save();

        GenerateTenantDataExportJob::dispatch($export->id);

        AuditLog::record(
            'tenant.data_export_approved',
            (int) $export->tenant_id,
            'super_admin',
            $sa?->id,
            $sa?->name,
            [
                'subject_type' => 'tenant_data_export_request',
                'subject_id'   => $export->id,
                'description'  => $description,
            ]
        );
    }
}
